const productSeed = [
  {
    name: 'Grey Calming Dog Tee',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/l_sale-badge,fl_relative,w_0.16,g_north_west,e_sharpen/3500086-center-15',
    petType: 'dog',
    clothingType: 'shirt',
    price: 19.99,
  },
  {
    name: 'Backcountry x Petco The Sun Shield Dog T-Shirt',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/l_sale-badge,fl_relative,w_0.16,g_north_west,e_sharpen/3478499-center-6',
    petType: 'dog',
    clothingType: 'shirt',
    price: 19.99,
  },
  {
    name: 'Reddy Yellow/Grey Colorblock Dog Tee',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/3473161-center-5',
    petType: 'dog',
    clothingType: 'shirt',
    price: 12.99,
  },
  {
    name: 'TieDye Dog BowTie',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/l_sale-badge,fl_relative,w_0.16,g_north_west,e_sharpen/3475677-center-3',
    petType: 'dog',
    clothingType: 'other',
    price: 4.99,
  },
  {
    name: 'Chambray Dress',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/3499708-center-5',
    petType: 'dog',
    clothingType: 'dress',
    price: 17.99,
  },
  {
    name: 'YOULY Flamingo Tulle Dog Dress',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/l_sale-badge,fl_relative,w_0.16,g_north_west,e_sharpen/3473743-center-14',
    petType: 'dog',
    clothingType: 'dress',
    price: 19.99,
  },
  {
    name: 'Varsity Dog Hoodie',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/l_sale-badge,fl_relative,w_0.16,g_north_west,e_sharpen/3500457-center-2',
    petType: 'dog',
    clothingType: 'coat',
    price: 25.99,
  },
  {
    name: 'Tropical Print Hoodie',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/3529479-center-1',
    petType: 'dog',
    clothingType: 'coat',
    price: 25.0,
  },
  {
    name: 'Floral Dog Sweater',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/3474068-center-3',
    petType: 'dog',
    clothingType: 'coat',
    price: 12.99,
  },
  {
    name: 'Grow-With-Me Dog Raincoat',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/l_sale-badge,fl_relative,w_0.16,g_north_west,e_sharpen/3545591-center-1',
    petType: 'dog',
    clothingType: 'coat',
    price: 65.99,
  },
  {
    name: 'Purrticular Tee',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/l_sale-badge,fl_relative,w_0.16,g_north_west,e_sharpen/3521725-center-6',
    petType: 'cat',
    clothingType: 'shirt',
    price: 12.99,
  },
  {
    name: 'Cat Printed Puffer',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/3420166-center-3',
    petType: 'cat',
    clothingType: 'coat',
    price: 10,
  },
  {
    name: 'Quilted Hoodie',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/3420140-center-7',
    petType: 'cat',
    clothingType: 'coat',
    price: 9,
  },
  {
    name: 'Floral Ruffle Cat Tee',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/3475491-center-4',
    petType: 'cat',
    clothingType: 'shirt',
    price: 12.99,
  },
  {
    name: 'Horse Blanket',
    image: 'https://m.media-amazon.com/images/I/51FQJ3lC-XL._AC_UL320_.jpg',
    petType: 'horse',
    clothingType: 'coat',
    price: 49.43,
  },
  {
    name: 'Tough 1 Zebra Mesh Fly Sheet Horse Coat',
    image: 'https://m.media-amazon.com/images/I/61kZ9BxzggL._AC_UL320_.jpg',
    petType: 'horse',
    clothingType: 'coat',
    price: 48.97,
  },
  {
    name: 'Horse Fly Mask Elasticity Fly Mask with Ears UV Protection for Horse',
    image: 'https://m.media-amazon.com/images/I/81toOFCNvOL._AC_UL320_.jpg',
    petType: 'horse',
    clothingType: 'other',
    price: 12.99,
  },
  {
    name: 'QUMY 2PCS Dog Boots for Hot Pavement Shoes',
    image: 'https://m.media-amazon.com/images/I/81-Vhjv3IwL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'shoes',
    price: 12.99,
  },
  {
    name: 'BEAUTYZOO Anti-Slip Dog Socks with Grips Traction Control',
    image: 'https://m.media-amazon.com/images/I/81UFmPxcMwL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'shoes',
    price: 12.99,
  },
  {
    name: 'QUMY 2PCS Small Dog Shoes-Pink',
    image: 'https://m.media-amazon.com/images/I/71eEbeUWnNL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'shoes',
    price: 12.99,
  },
  {
    name: 'YAODHAOD Dog Shoes ',
    image: 'https://m.media-amazon.com/images/I/71+i-jkLv2L._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'shoes',
    price: 11.99,
  },
  {
    name: 'JOPE 4pcs Silicone Cat Boots Anti Scratch',
    image: 'https://m.media-amazon.com/images/I/514EU2gmfwL._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'shoes',
    price: 10.99,
  },
  {
    name: 'GabeFish Puppy Snow Booties',
    image: 'https://m.media-amazon.com/images/I/71Tw5rwb8gL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'shoes',
    price: 11.99,
  },
  {
    name: 'Champ 4 Pcs Cartoon Graphic Anti Slip Socks',
    image: 'https://m.media-amazon.com/images/I/71SQJrrb1aS._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'shoes',
    price: 12.99,
  },
  {
    name: 'GAPZER Anti-Scratch Cat Shoes',
    image: 'https://m.media-amazon.com/images/I/71EbAjac+pL._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'shoes',
    price: 12.99,
  },
  {
    name: 'Pet Bikini',
    image: 'https://m.media-amazon.com/images/I/817FLfEk6SL._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'swim',
    price: 8.99,
  },
  {
    name: 'ALAGIRLS Dog Shark Life Jacket for Swimming Boating',
    image: 'https://m.media-amazon.com/images/I/71c7Qgw-7lL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'swim',
    price: 24.99,
  },
  {
    name: 'Calming Ear Muffs',
    image: 'https://m.media-amazon.com/images/I/71dkMGdyq7S._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'other',
    price: 14.99,
  },
  {
    name: 'MORVIGIVE Rainbow Dog Bikini ',
    image: 'https://m.media-amazon.com/images/I/710xluUD0UL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'swim',
    price: 12.99,
  },
  {
    name: 'Dog Bikini Swimsuit Summer Puppy',
    image: 'https://m.media-amazon.com/images/I/61PJ0ll53DL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'swim',
    price: 12.99,
  },
  {
    name: 'Dog Life Jackets, Ripstop Pet Floatation ',
    image: 'https://m.media-amazon.com/images/I/71vgo2wI0NL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'swim',
    price: 43.99,
  },
  {
    name: 'Phyxin Dog Life Jacket Adjustable',
    image: 'https://m.media-amazon.com/images/I/61VGazquEzL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'swim',
    price: 12.99,
  },
  {
    name: 'iPet Princess Floral Cat Party Bridal Wedding Dress',
    image: 'https://m.media-amazon.com/images/I/710DTICk4FL._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'dress',
    price: 13.99,
  },
  {
    name: 'Cat Santa',
    image: 'https://m.media-amazon.com/images/I/61vw-pXxsmL._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'shirt',
    price: 12.99,
  },
  {
    name: 'HYLYUN Guinea Pig Clothes',
    image: 'https://m.media-amazon.com/images/I/71auHaNmauL._AC_UL320_.jpg',
    petType: 'other',
    clothingType: 'shirt',
    price: 12.99,
  },
  {
    name: '3 Pieces Guinea Pig Harness with Leash ',
    image: 'https://m.media-amazon.com/images/I/81CrLIj07OS._AC_UL320_.jpg',
    petType: 'other',
    clothingType: 'other',
    price: 12.99,
  },
  {
    name: 'CooShou 4 Pieces Bunny Clothes',
    image: 'https://m.media-amazon.com/images/I/71ISX-nW6EL._AC_UL320_.jpg',
    petType: 'other',
    clothingType: 'shirt',
    price: 23.99,
  },
  {
    name: 'Winter Warm Fleece Bunny Shirt',
    image: 'https://m.media-amazon.com/images/I/51N3qx6iQQL._AC_UL320_.jpg',
    petType: 'other',
    clothingType: 'shirt',
    price: 9.99,
  },
  {
    name: 'Bunny Strawberry Dress',
    image: 'https://m.media-amazon.com/images/I/71TdZR-7twL._AC_UL320_.jpg',
    petType: 'other',
    clothingType: 'dress',
    price: 12.99,
  },
  {
    name: 'PetBoBo Doggie Down Jacket',
    image: 'https://m.media-amazon.com/images/I/51ga7CEmwmL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'coat',
    price: 23.99,
  },
  {
    name: 'Carhartt Dog Coat',
    image: 'https://m.media-amazon.com/images/I/91rCjeAylRL._AC_UX679_.jpg',
    petType: 'dog',
    clothingType: 'coat',
    price: 234.99,
  },
  {
    name: 'blu&ben Stylish Dog Coat',
    image: 'https://m.media-amazon.com/images/I/71j8M3h5uyL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'coat',
    price: 34.99,
  },
  {
    name: 'Izefia Dog Coat Cold Weather',
    image: 'https://m.media-amazon.com/images/I/518+mXsv-YL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'coat',
    price: 64.99,
  },
  {
    name: 'Cat Sweater-Grey',
    image: 'https://m.media-amazon.com/images/I/81tWZrpTgML._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'coat',
    price: 4.99,
  },
  {
    name: 'Anelekor Pet Bee Coat',
    image: 'https://m.media-amazon.com/images/I/61ZNmWUS+fS._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'coat',
    price: 9.99,
  },
  {
    name: 'HDE Dog Raincoat Double Layer Zip Rain Jacket',
    image: 'https://m.media-amazon.com/images/I/61ARA+i4ZjS._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'coat',
    price: 37.99,
  },
  {
    name: 'Canada Pooch Dog Rain Jacket',
    image: 'https://m.media-amazon.com/images/I/81rOg+AtatL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'coat',
    price: 50.87,
  },
  {
    name: 'Purple Dog Rain jacket',
    image: 'https://m.media-amazon.com/images/I/61RYmsfoAgL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'coat',
    price: 19.56,
  },
  {
    name: 'Goat Coat',
    image: 'https://m.media-amazon.com/images/I/51kYfHACTnL._AC_UL320_.jpg',
    petType: 'other',
    clothingType: 'coat',
    price: 47.63,
  },
  {
    name: 'Wind Storm Horse Cover',
    image: 'https://m.media-amazon.com/images/I/61qD0Qe3+6L._AC_UL320_.jpg',
    petType: 'horse',
    clothingType: 'coat',
    price: 56.87,
  },
  {
    name: 'Horze Nevada 1200D Waterproof Turnout Sheet - Black - Size: 84',
    image: 'https://m.media-amazon.com/images/I/71eMe8pVbBL._AC_UL320_.jpg',
    petType: 'horse',
    clothingType: 'coat',
    price: 108.76,
  },
  {
    name: 'Legendog Cat Bandana for Cats',
    image: 'https://m.media-amazon.com/images/I/71CppwFeWSS._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'other',
    price: 12.99,
  },
  {
    name: 'Cat Tee',
    image: 'https://m.media-amazon.com/images/I/51eXiP8qH0L._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'shirt',
    price: 12.99,
  },
  {
    name: 'Strawb Cat Dress',
    image: 'https://m.media-amazon.com/images/I/61-uI1Mg7GS._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'dress',
    price: 12.99,
  },
  {
    name: 'Cute Pink Dog Dress',
    image: 'https://m.media-amazon.com/images/I/61qlQ1MndfL._AC_UL320_.jpg',
    petType: 'dog',
    clothingType: 'dress',
    price: 12.99,
  },
  {
    name: 'YuDanae Animal Tom Shirt Hood',
    image: 'https://m.media-amazon.com/images/I/71fOKxUsEaL._AC_UL320_.jpg',
    petType: 'cat',
    clothingType: 'shirt',
    price: 14.93,
  },
  {
    name: 'Colorblock Cat Tee',
    image:
      'https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_636,w_636/c_pad,h_636,w_636/3473217-center-3',
    petType: 'cat',
    clothingType: 'shirt',
    price: 12.21,
  },
];

module.exports = productSeed;

let template = {
  name: '',
  image: '',
  petType: 'cat',
  clothingType: 'shirt',
  price: 12.21,
};
